
server:
  port: 8000

spring:
  cloud:
    gateway:
      routes:
        - id: first-service
          uri: http://localhost:8080
          predicates:
            - Path=/first-service/**
        - id: second-service
          uri: http://localhost:8081
          predicates:
            - Path=/second-service/**
          filters:
            - AddRequestHeader=second-request, second-request-header
            - AddResponseHeader=second-response, second-response-header

management:
  endpoints:
    web:
      exposure:
        include:
          - "gateway"
  endpoint:
    gateway:
      enabled: true