server:
  port: 9000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: first-service
          uri: lb://eureka-service-1
          predicates:
            - Path=/first-service/**
        - id: second-service
          uri: lb://eureka-service-2
          predicates:
            - Path=/second-service/**
